services:
  equilibrium-bot:
    image: ghcr.io/thealmostsentienttoaster/equilibrium-bot
    container_name: equilibrium-bot
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:8080"