services:
  equilibrium-bot:
    image: ghcr.io/thealmostsentienttoaster/equilibrium
    container_name: equilibrium-bot
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:8080"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    environment:
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=${EMAIL_FROM}
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=${EMAIL_TO}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=protonmail-bridge
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=1025
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=${PROTONMAIL_USERNAME}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=${BRIDGE_GENERATED_PASSWORD}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_TLS=false
      - WATCHTOWER_NOTIFICATION_EMAIL_SUBJECT_TEMPLATE=Watchtower Update {{.Container}}
      - WATCHTOWER_NOTIFICATION_EMAIL_BODY_TEMPLATE=Container {{.Container}} was updated. Logs:\n\n{{.Logs}}
    command: >
      --schedule "*/10 23 * * *"
      --cleanup
      --label-enable
      --notifications email